from pylab import *
infile = open('2D.txt', 'r')
x,y,z = loadtxt(infile, unpack=True)
plot(x,y,z)
#plot.xlabel('Smarts')
#plot.ylabel('Probability')
#plot.title('Histogram of IQ')
#plot.text(60, .025, r'$\mu=100,\ \sigma=15$')
#plot.axis([40, 160, 0, 0.03])
#plot.grid(True)
show()